name = "r2-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "content.r24.dev/*"
zone_name = "r24.dev"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true